### ISSUE TITLE
ncpmount failed, error: ncpmount: No such device in mount(2)

### ISSUE THREAD

**Issue by bpranoto** [pasis/ipx#3]
Although I can login to a netware server, mounting with ncpmount failed:

```
akunting@akunting:~/dosemu2/20.04/64bits$ sudo ncpmount -S berkah -U bambang -u 1000 -g 1000 /media/server
Logging into berkah as BAMBANG
Password: 
ncpmount: No such device in mount(2)

akunting@akunting:~/dosemu2/20.04/64bits$ ncpmount -v
ncpfs version 2.2.6


```

Many google search result this is due to lack of ncpfs kernel module. Can you please help? Thank you.

**Comment by bpranoto** [comment]
Found this: https://github.com/EnzephaloN/ncpfs_dkms

**Comment by pasis** [comment]
Thank you for the link, I've added it to README.
