### ISSUE TITLE
kernel 6.3.1

### ISSUE THREAD

**Issue by geosone** [pasis/ipx#6]
`* Determining the location of the kernel source code
 * Found kernel source directory:
 *     /usr/src/linux
 * Found sources for kernel version:
 *     6.3.1-xanmod1-dist
 * Checking for suitable kernel configuration options ...                                                                                                                                                  [ ok ]
>>> Unpacking source...
 * Repository id: pasis_ipx.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_PASIS_IPX
 *   EGIT_OVERRIDE_BRANCH_PASIS_IPX
 *   EGIT_OVERRIDE_COMMIT_PASIS_IPX
 *   EGIT_OVERRIDE_COMMIT_DATE_PASIS_IPX
 * 
 * Fetching https://github.com/pasis/ipx.git ...
git fetch https://github.com/pasis/ipx.git +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/net-misc/ipx-modules/0/__main__ refs/git-r3/HEAD
 * Checking out https://github.com/pasis/ipx.git to /var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://github.com/pasis/ipx.git
   at the commit:            dddfe2270f7360860179e029a9c026345e57bc08
>>> Source unpacked in /var/tmp/portage/net-misc/ipx-modules-9999/work
>>> Preparing source in /var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999 ...
ln: failed to create symbolic link 'Module.symvers': File exists
 * Preparing ipx module
make -j12 -s HOSTCC=x86_64-pc-linux-gnu-gcc 'LDFLAGS=-m elf_x86_64' KERNELDIR=/usr/src/linux M=/var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999 build 
Building with KERNELRELEASE = 6.3.1-xanmod1-dist
/var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999/af_ipx.c: In function ‘ipx_destroy_socket’:
/var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999/af_ipx.c:141:9: error: implicit declaration of function ‘sk_refcnt_debug_dec’ [-Werror=implicit-function-declaration]
  141 |         sk_refcnt_debug_dec(sk);
      |         ^~~~~~~~~~~~~~~~~~~
/var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999/af_ipx.c: In function ‘ipx_create’:
/var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999/af_ipx.c:1373:9: error: implicit declaration of function ‘sk_refcnt_debug_inc’ [-Werror=implicit-function-declaration]
 1373 |         sk_refcnt_debug_inc(sk);
      |         ^~~~~~~~~~~~~~~~~~~
/var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999/af_ipx.c: In function ‘ipx_release’:
/var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999/af_ipx.c:1396:9: error: implicit declaration of function ‘sk_refcnt_debug_release’ [-Werror=implicit-function-declaration]
 1396 |         sk_refcnt_debug_release(sk);
      |         ^~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:252: /var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999/af_ipx.o] Error 1
make[1]: *** [Makefile:2180: /var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999] Error 2
make: *** [Makefile:7: build] Error 2
 * ERROR: net-misc/ipx-modules-9999::linamh failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=net-misc/ipx-modules-9999::linamh'`,
 * the complete build log and the output of `emerge -pqv '=net-misc/ipx-modules-9999::linamh'`.
 * The complete build log is located at '/var/tmp/portage/net-misc/ipx-modules-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-misc/ipx-modules-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999'
 * S: '/var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999'
`

**Comment by pasis** [comment]
Thank you for the report. I will take a look once I have a chance.

Could you share ebuild for "ipx-modules"? I cannot find it in any overlay.

**Comment by geosone** [comment]
[ipx-modules-9999.ebuild.txt](https://github.com/pasis/ipx/files/11461920/ipx-modules-9999.ebuild.txt)

normally i woudl point you to my site but the server hosting nginx proxy manager was fried by the last electric spike.

**Comment by pasis** [comment]
Should be fixed in master

**Comment by pasis** [comment]
And thank you for the ebuild!

**Comment by geosone** [comment]
yes it si compiling also with 6.3.2 
by the way do you know an example systemd file for the ipx_utils ipx_configure ...

**Comment by pasis** [comment]
I don't have experience with systemd. Basically, I configure IPX manually when I use it (what happens quite rarely).

**Comment by geosone** [comment]
its working thx

**Comment by geosone** [comment]
just for info my overlay wiht the ipx-utils ncpfs ncpfs-modules mars-nwe ...
https://gitea.disconnected-by-peer.at/dbp/linamh

**Comment by pasis** [comment]
thanks for sharing
