### ISSUE TITLE
Build Problems with 6.8.0

### ISSUE THREAD

**Issue by geosone** [pasis/ipx#8]
` * Determining the location of the kernel source code
 * Found kernel source directory:
 *     /usr/src/linux
 * Found sources for kernel version:
 *     6.8.0-xanmod1-dist
 * Checking for suitable kernel configuration options ...                                                                                                                                                  [ ok ]
>>> Unpacking source...
 * Repository id: pasis_ipx.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_PASIS_IPX
 *   EGIT_OVERRIDE_BRANCH_PASIS_IPX
 *   EGIT_OVERRIDE_COMMIT_PASIS_IPX
 *   EGIT_OVERRIDE_COMMIT_DATE_PASIS_IPX
 * 
 * Fetching https://github.com/pasis/ipx.git ...
git fetch https://github.com/pasis/ipx.git +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/net-misc/ipx-modules/0/__main__ refs/git-r3/HEAD
 * Checking out https://github.com/pasis/ipx.git to /var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://github.com/pasis/ipx.git
   at the commit:            4996f0cc7ef66bc2c3113bc461869c49f9bafdc2
>>> Source unpacked in /var/tmp/portage/net-misc/ipx-modules-9999/work
>>> Preparing source in /var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999 ...
ln: failed to create symbolic link 'Module.symvers': File exists
 * Preparing ipx module
make -j12 -s HOSTCC=x86_64-pc-linux-gnu-gcc 'LDFLAGS=-m elf_x86_64' KERNELDIR=/usr/src/linux M=/var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999 build 
Building with KERNELRELEASE = 6.8.0-xanmod1-dist
/var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999/pe2.c:26:24: warning: no previous prototype for ‘make_EII_client’ [-Wmissing-prototypes]
   26 | struct datalink_proto *make_EII_client(void)
      |                        ^~~~~~~~~~~~~~~
/var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999/pe2.c:38:6: warning: no previous prototype for ‘destroy_EII_client’ [-Wmissing-prototypes]
   38 | void destroy_EII_client(struct datalink_proto *dl)
      |      ^~~~~~~~~~~~~~~~~~
/var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999/p8023.c:47:24: warning: no previous prototype for ‘make_8023_client’ [-Wmissing-prototypes]
   47 | struct datalink_proto *make_8023_client(void)
      |                        ^~~~~~~~~~~~~~~~
/var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999/p8023.c:61:6: warning: no previous prototype for ‘destroy_8023_client’ [-Wmissing-prototypes]
   61 | void destroy_8023_client(struct datalink_proto *dl)
      |      ^~~~~~~~~~~~~~~~~~~
/var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999/af_ipx.c: In function ‘__ipx_bind’:
/var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999/af_ipx.c:1512:17: error: implicit declaration of function ‘SOCK_DEBUG’; did you mean ‘SO_DEBUG’? [-Werror=implicit-function-declaration]
 1512 |                 SOCK_DEBUG(sk, "IPX: bind failed because port %X in use.\n",
      |                 ^~~~~~~~~~
      |                 SO_DEBUG
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:243: /var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999/af_ipx.o] Error 1
make[2]: *** [/usr/src/linux-6.8.0-xanmod1-dist/Makefile:2073: /var/tmp/portage/net-misc/ipx-modules-9999/work/ipx-modules-9999] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make: *** [Makefile:7: build] Error 2
 * ERROR: net-misc/ipx-modules-9999::linamh failed (compile phase):
`

**Comment by pasis** [comment]
Thanks for report, I will check

**Comment by geosone** [comment]
thx

**Comment by pasis** [comment]
Should be fixed in master

**Comment by geosone** [comment]
thx compiles will test this weekend
